import Head from "next/head";
import Navbar from "../components/navbar";

import styles from "../styles/about.module.css";
import { useState } from "react";

export default function Home() {
  let [SelectMenuTF, SelectMenuTFEd] = useState(false);
  return (
    <>
      <Head>
        <title>DISEOCOLL - 소개</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="app"
        onClick={() => {
          SelectMenuTFEd;
        }}
      >
        <Navbar
          links="true"
          SelectMenuTF={SelectMenuTF}
          SelectMenuTFEd={SelectMenuTFEd}
        />
        <div
          className={styles.container}
          onClick={() => {
            SelectMenuTFEd(false);
          }}
        >
          <h1 className={styles.title}>DISEOCOLL</h1>
          <p className={styles.meaning}>Discord Server Collect</p>

          <h2 className={styles.subtitle}>개발자 목록</h2>
          <ul className={styles.list}>
            <li>! 대찌#4559 (프론트엔드, 백엔드)</li>
            <li>! レムリン#9999 - (백엔드)</li>
            <li>현성#9999 - (기획)</li>
          </ul>

          <h2 className={styles.subtitle}>디스코드 서버</h2>
          <p className={styles.purpose}>
            질문사항, 모든 문의는{" "}
            <a href="https://diseocoll.com/support" target={"_blank"}>
              디서콜 공식 서버
            </a>{" "}
          </p>

          <h2 className={styles.subtitle}>웹사이트 기능 - 보안관련 기능</h2>
          <ol className={styles.steps}>
            <li>
              <h3 className={styles.stepTitle}>보안 하 : 초대코드 지정</h3>
              <p className={styles.stepDesc}>
                누구나 서버에 접속할 수 있습니다.
              </p>
            </li>
            <li>
              <h3 className={styles.stepTitle}>
                보안 중 : 매번 1회용 코드 사용
              </h3>
              <p className={styles.stepDesc}>
                로그인 한 유저만 접속할 수 있으며 초대 링크 하나로 여러 명의
                유저가 들어올 수 없어 토큰 테러를 방지할 수 있습니다.
              </p>
            </li>
            <li>
              <h3 className={styles.stepTitle}>
                보안 상 : 서버 참여하기 클릭 시 유저를 서버에 자동으로 참여
              </h3>
              <p className={styles.stepDesc}>
                초대코드가 아닌 oauth2 방식을 사용하여 서버에 입장됩니다.
                <br />
                이는 초대코드를 사용하지 않기에 초대자 확인이 어려울 수
                있습니다.
                <br />* 알로항봇 입장로그 기능을 이용하시면 초대자를 확인할 수
                있습니다
              </p>
            </li>
          </ol>
        </div>
      </div>
    </>
  );
}
